### ISSUE TITLE
Implement group retrieval

### ISSUE THREAD

**Issue by psy-farrell** [am8302/groupingModel#2]
Assume people "tag" the first group

And then retrieve a group context according to Eqs A5-A7 (and related equations)

Ignore timing (assume, e.g., p_j^{CG} = 1)

Assume all groups are on the current list

**Comment by alicemason** [comment]
Attempted to add group context - confused by tagging first group as would this not lead to control element for that group being activated?

**Comment by psy-farrell** [comment]
I’ve made a commit to keep things ticking along
On 11 May 2015, at 11:51 am, Alice Mason <notifications@github.com<mailto:notifications@github.com>> wrote:

Attempted to add group context - confused by tagging first group as would this not lead to control element for that group being activated?
