### ISSUE TITLE
Implement multiple retrievals

### ISSUE THREAD

**Issue by psy-farrell** [am8302/groupingModel#3]
Assume people make a fixed number of recall attempts, let's say 3. Assume that ppl make N recall attempts per group, where N is the size of that group. You will need to rescale the within-group positional markers based on group size. Don't worry about response suppression or output interference for the moment. Remember, we assume sequential access, so if the group contains 3 items, we use the within group cue for the first item, then the 2nd, then the third.

You'll probably want to reorganise your code, as we don't need to retrieve the group marker again each time we recall from the same group, only when we access a new group

**Comment by am8302** [comment]
So I should end up with each item on the list being recalled? If people make N attempts per group.

**Comment by psy-farrell** [comment]
If there isn’t any response suppression you’ll probably have a fair number of repetitions

S

On 12 May 2015, at 3:15 pm, Alice Mason <notifications@github.com<mailto:notifications@github.com>> wrote:

So I should end up with each item on the list being recalled? If people make N attempts per group.

**Comment by alicemason** [comment]
I didn't phrase that last question properly - I meant to ask if you the context cue stays at 1? So they are simply attempting N items on 1st list? And the current selection process this will basically always be the first item.

**Comment by psy-farrell** [comment]
No, once they have made N recall attempts for one group, retrieve another group context. And within-group cue won’t stay at first item, as per my previous comments

S

On 12 May 2015, at 3:30 pm, Alice Mason <notifications@github.com<mailto:notifications@github.com>> wrote:

I didn't phrase that last question properly - I meant to ask if you the context cue stays at 1? So they are simply attempting N items on 1st list? And the current selection process this will basically always be the first item.

**Comment by psy-farrell** [comment]
Looks like it is doing the right thing
