### ISSUE TITLE
Implement response suppression and output interference

### ISSUE THREAD

**Issue by psy-farrell** [am8302/groupingModel#4]
- Response suppression should be straightforward
- Output interference occurs at level of groups---let me know if you need help

**Comment by alicemason** [comment]
@psy-farrell 
something isn't right with my output interference as the code now only works for outpos =1:4

**Comment by psy-farrell** [comment]
Can you sync to github and I’ll have a look

S

On 13 May 2015, at 11:38 pm, Alice Mason <notifications@github.com<mailto:notifications@github.com>> wrote:

@psy-farrellhttps://github.com/psy-farrell
something isn't right with my output interference as the code now only works for outpos =1:4

**Comment by alicemason** [comment]
Have just synced.
