### ISSUE TITLE
Implement Experiment 2 (Two) in Erev and contingent sampling model

### ISSUE THREAD

**Issue by psy-farrell** [am8302/groupingModel#9]
This is bottom half of Figure 2, and more interesting in discriminating between the models

**Comment by alicemason** [comment]
This has worked fine for Contingent Sampling but not for Fictitious play. Makes me think something was wrong with Fictitious play code as all I've done is to change the demoted option from 8 to 2.

**Comment by psy-farrell** [comment]
Yes, running sims like this is good error checking. Have a look at the FP code again and see if you can track down error.

On 18 May 2015, at 3:05 pm, Alice Mason <notifications@github.com<mailto:notifications@github.com>> wrote:

This has worked fine for Contingent Sampling but not for Fictitious play. Makes me think something was wrong with Fictitious play code as all I've done is to change the demoted option from 8 to 2.
